# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  projetdotnetgasmielharouimazyadkoubikani:
    image: projetdotnetgasmielharouimazyadkoubikani
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8090
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
